# Workflow for credential-proving benchmarks
name: Run benchmarks

on:
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

concurrency:
  group: "benchmark"
  cancel-in-progress: false

jobs:
  benchmark:
    runs-on: ubuntu-latest-l

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup env
        uses: ./.github/actions/setup
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install & build packages
        run: |
          pnpm i
          pnpm run build

      - name: Run benchmarks
        run: pnpm run benchmark

      - name: Commit benchmark results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          if git show-ref --quiet refs/remotes/origin/benchmark-results; then
            git fetch origin benchmark-results
            git checkout benchmark-results
            git merge FETCH_HEAD
          else
            git checkout -b benchmark-results
          fi

          git add .
          git commit -m "Update benchmark results" || echo "No changes to commit"
          git push origin benchmark-results